// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlsjzuauqihseruqygdv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsc2p6dWF1cWloc2VydXF5Z2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2ODk4NTYsImV4cCI6MjA4MjI2NTg1Nn0.kCgE0UK0JNro8dUjHPRbrAdh_9Cm4S38nVmHdjA9YRI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});