// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fldtatupnyfseyicvmau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZsZHRhdHVwbnlmc2V5aWN2bWF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MDE0OTYsImV4cCI6MjA3MjM3NzQ5Nn0.z38zBvNjJ6QgSFTkoHRZ9z9AELXbljO9l5IXX4nZeWM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});